tetrate:
  clientId: tetrate-trader
  accountServiceUrl: 'http://localhost:8082'
  portfolioServiceUrl: 'http://localhost:8083'
  quoteServiceUrl: 'http://localhost:8081'
spring:
  application:
     name: web-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  config:
    import: 'optional:configserver:'
  cloud:
    discovery:
      enabled: false
  security:
    oauth2:
      client:
        registration: 
          keycloak: 
            client-id: ${tetrate.clientId}
            client-secret: tetrate-trader
            scope: openid
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: https://keycloak.cloud.zwickey.net/auth/realms/tetrate
            
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
info:
  build:
    group: ${group}
    name: ${name}
    description: ${description}
    version: ${version}
logging:
  level:
    io.tetrate: DEBUG
    org.springframework.security: WARN